kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  namespace: test
data:
  password: NWM4OTVjMzc2MDk2OTIxNmI0NjljN2Y2OWE5MjA4YmU=
---
kind: Secret
apiVersion: v1
metadata:
  name: redis-cluster-secret
  namespace: test
data:
  password: YzcwMDBkNjVlYTE2ZjcxMDczNzQzZjgwODc2NGUxNmM=
---
kind: Secret
apiVersion: v1
metadata:
  name: redis-lock-secret
  namespace: test
data:
  password: NGRlM2MxMjI4NmJmMWQ2MWU2NTFlMTEwY2Y2ZTM2NjA=
